// Autogenerated weights for `pallet_infostratus`
// THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
// For details, see backup in BACKUPSWW/WorkingVersionfennel-solonet-bmark-deterministic
#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_infostratus`.
pub trait WeightInfo {
	fn create_submission_entry() -> Weight;
	fn create_submission_entry_heavy_storage() -> Weight;
	fn request_submission_assignment() -> Weight;
	fn request_submission_assignment_heavy_storage() -> Weight;
}

/// Weights for `pallet_infostratus` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_submission_entry() -> Weight {
		Weight::from_parts(63_570_000, 4764)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn create_submission_entry_heavy_storage() -> Weight {
		Weight::from_parts(125_901_000, 4764)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn request_submission_assignment() -> Weight {
		Weight::from_parts(57_833_000, 4764)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn request_submission_assignment_heavy_storage() -> Weight {
		Weight::from_parts(145_383_000, 4764)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_submission_entry() -> Weight {
		Weight::from_parts(63_570_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn create_submission_entry_heavy_storage() -> Weight {
		Weight::from_parts(125_901_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn request_submission_assignment() -> Weight {
		Weight::from_parts(57_833_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn request_submission_assignment_heavy_storage() -> Weight {
		Weight::from_parts(145_383_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
