name: Deterministic Runtime Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  srtool-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.9.2
        with:
          chain: solochain
          runtime_dir: runtime
          package: solochain-template-runtime
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > srtool-digest.json
          cat srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
      - name: Archive Runtime
        uses: actions/upload-artifact@v2
        with:
          name: solochain-runtime-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            srtool-digest.json 