name: Srtool build

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.8.0
        with:
          chain: solochain
          runtime_dir: runtime
          package: solochain-template-runtime
          
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > solochain-srtool-digest.json
          cat solochain-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
          
      - name: Archive Runtime
        uses: actions/upload-artifact@v2
        with:
          name: solochain-runtime-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            solochain-srtool-digest.json